### ISSUE TITLE
Package and Module Names Modules should have short, all-lowercase names.

### ISSUE THREAD

**Issue by tisto** [MrTango/RISparser#1]
"Package and Module Names Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged."

http://www.python.org/dev/peps/pep-0008/

**Comment by shapiromatron** [comment]
@tisto still have a need for this? I'm taking over maintenance of this project and will change if needed.

**Comment by tisto** [comment]
@shapiromatron I do not have any interest in this package any longer. Feel free to do whatever you think makes sense...
