### ISSUE TITLE
the map of SE to 'version' correct?

### ISSUE THREAD

**Issue by Xunius** [MrTango/RISparser#14]
Hi
I noticed that the tag 'SE' in mapped to key of 'version', while in wikipedia the tag as a meaning of 'Sections'. I didn't find other places giving a definition of 'SE'. Could this be a mistake? Maybe add a note in the doc?

Also, both 'AB' and 'M1' are mapped to 'abstract'. My tests seem to suggests that whichever comes first get extracted. Maybe adding a line regarding this behavior in the doc?

**Comment by shapiromatron** [comment]
Sorry for the delay. 

Thanks, we'll change `SE` to section; wikipedia seems like a good reference.

We recently changed `N2` to be `notes_abstract`, and kept `AB`: `abstract`. This makes the remapping different.

@MrTango do you know of any more formal mapping of RIS keys than wikipedia?

**Comment by MrTango** [comment]
I only found this https://forums.zotero.org/discussion/70151/ris-import-archival-location-ris-av-field
the original spec from refman is down, but there is an archive link: https://web.archive.org/web/20120526103719/http://refman.com/support/risformat_intro.asp

**Comment by shapiromatron** [comment]
I found the source of the original SE version mapping; it's from an XLS you can download here. https://web.archive.org/web/20120526103719/http://refman.com/support/risformat_intro.asp.

I'm fine changing SE as section though, I think that's the original intent given the characters.

**Comment by shapiromatron** [comment]
Changed in v0.5.0
