### ISSUE TITLE
IndexError if first line is blank

### ISSUE THREAD

**Issue by rafguns** [MrTango/RISparser#3]
If the first line of the RIS file is blank, an `IndexError` is raised at https://github.com/MrTango/RISparser/blob/master/RISparser/__init__.py#L70

This could be fixed by wrapping in a `try: ... except IndexError: pass` block.

**Comment by shapiromatron** [comment]
Does the RIS file specification allow for an empty first line? Or, if it's ambiguous, can you upload an RIS file into Endnote with an empty first line?

**Comment by rafguns** [comment]
It's not clear in the RIS format specs, but Endnote happily imports files that start with one or more empty lines.

**Comment by shapiromatron** [comment]
@rafguns Turns out I had the same issue today w/ an RIS file I received from a third-party; I just released v0.4.3 that fixes this.
