### ISSUE TITLE
Two Way RISParser

### ISSUE THREAD

**Issue by OliJimbo** [MrTango/RISparser#7]
Hi Maik!  Thank you for this package - it is really useful!

I've been using it to compare two RIS files for a meta-analysis (I lost a day playing with XML parsing and then found this!).

I was wondering how much of an ordeal it would be to make RISparser a two way street.  That is, how much effort would it take to turn the dictionaries back into importable RIS files?  I'd be happy to take a crack at it, but would like to hear your expert thoughts on it first!

I'd assume it would be a matter of matching the dictionary keys with the ```TAG_KEY_MAPPING``` and then using formatted strings to insert the values - but my python is pretty basic!

Thanks again!

Oli

**Comment by shapiromatron** [comment]
@OliJimbo interesting idea, not sure it belongs in this repository, though if you want to submit a PR I could review. I think it'd be pretty simple, each dictionary in a list of dictionaries would convert to an RIS entry as you suggested. Authors would expect a list of values for example would would translate to multiple rows in the RIS file.
