### ISSUE TITLE
Suggest to change 'LIST_TYPE_TAGS' from tuple to list type

### ISSUE THREAD

**Issue by emilyzzz** [MrTango/RISparser#8]
Currently LIST_TYPE_TAGS is tuple type:
```
from RISparser.config import LIST_TYPE_TAGS
print(type(LIST_TYPE_TAGS))
```

If someone wants to extend the current ris_parser and add a new type as a list_type, he can't override it, since it's tuple and immutable.  Ideally, we would want users to extend as they desired, something similar to:
```
from RISparser.config import LIST_TYPE_TAGS
LIST_TYPE_TAGS.append('XY')     # 'XY' being some RIS tags
```

There's example use case:  currently the ris_parser doesn't handle "ED" field, which could be multiple lines. If LIST_TYPE_TAGS is a list type, this use case can simply be solved.

**Comment by shapiromatron** [comment]
Hi @emilyzzz, thanks! I accepted your PR; let me know if you need a new version on pypi otherwise I'll just wait for a few other minor changes.
